=== fgelati/significantproperties/sigprops.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://slubarchiv.slub-dresden.de/sigprops1"
    xmlns="http://slubarchiv.slub-dresden.de/sigprops1" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified" version="1.0">
    <xs:annotation>
        <xs:documentation>XML files that are created based on this Schema describe exactly one
            digital object type. If your collection contains more than one object types, please create more
            XML files. The schema only describes the final result of determining significant
            properties for an object type. Workflow specific data are not
            captured. 
        </xs:documentation>
    </xs:annotation>

    <xs:element name="ObjectType">
        <xs:complexType>
            <xs:all>
                <xs:element name="Metadata" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="CreationDate" type="xs:dateTime" minOccurs="1"
                                maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>Date, Time and Timezone of the moment when the
                                        XML was created.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="Creator" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>Person / Role who created this
                                        XML.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="WorkflowName" type="xs:string" minOccurs="1"
                                maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>Name of the Workflow that this Object is being
                                        produced with.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="InstitutionName" type="xs:string" minOccurs="1"
                                maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>Name of the Institution that created the
                                        Object.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="InstitutionContact" type="xs:string" minOccurs="1"
                                maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>Contact information of a person or group at
                                        the Institution that created the Object.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="ObjectTypeName" type="xs:string" minOccurs="1"
                                maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>Name of the Objecttype that is described in the
                                        XML.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>

                <xs:element name="SignificantProperties" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SignificantProperty" type="typeSignificantProperty"
                                minOccurs="1" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:documentation>Catalog of Significant Property
                                        nodes.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:all>
            <xs:attribute name="resourceType" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>Name of the resource. A resource is a specific subtype of an object. 
                        This is useful when expressing that certain significant properties are particularly associated with specific parts of an object.
                        
                        An example:
                        there is an object type "article". If we want to express that a certain component of this object type, let's say "mathematical formula",
                        has special significant properties, e.g. "is machine readable", then it makes sense to bind these properties not generally to the 
                        object type "article", but to the object type "article" with resource type "Mathematical formula".
                        
                        In general it is not necessary to specify resource types.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute default="en" name="language" type="xs:language" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        Specifies the encoding language for current Objecttype. The default is 'en' for english.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="typeSignificantProperty">
        <xs:all>
            <xs:element name="PropertyName" type="xs:string" minOccurs="1" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>Name of the significant property.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="PropertyExplanation" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>More detailed explanation of why this property is
                        significant.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string"> </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="PropertyCategory" type="typeCategory" minOccurs="1" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>One of the five categories that significant properties can be
                        assigned (Content, Context, Structure, Rendering,
                        Behavior).</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="PropertyProcedure" type="typeProcedure" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>Specifies the procedure that was used to find this significant
                        property.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>
    <xs:simpleType name="typeProcedure">
        <xs:restriction base="xs:string">
            <xs:enumeration value="provenance">
                <xs:annotation>
                    <xs:documentation> Specifies a procedure to determine the significant properties based on a provenance approach using the original intention of the creator of the object </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="designated communities">
                <xs:annotation>
                    <xs:documentation> Specifies a procedure to determine significant properties based on possible, future usage scenarios of a designated community.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="typeCategory">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Content">
                <xs:annotation>
                    <xs:documentation> Specifies a significant property that preserves
                        the object's content. </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Context">
                <xs:annotation>
                    <xs:documentation> Specifies a significant property that preserves
                        the object's Context. </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Structure">
                <xs:annotation>
                    <xs:documentation> Specifies a significant property that preserves
                        the object's Structure. </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Rendering">
                <xs:annotation>
                    <xs:documentation> Specifies a significant property that preserves
                        the object's Rendering. </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Behaviour">
                <xs:annotation>
                    <xs:documentation> Specifies a significant property that preserves
                        the object's Behaviour. </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== fgelati/significantproperties/sigprops_retromuenzen.xml
<?xml version="1.0" encoding="UTF-8"?>
<ObjectType xmlns="http://slubarchiv.slub-dresden.de/sigprops1"
    xsi:schemaLocation="http://slubarchiv.slub-dresden.de/sigprops1 https://slubarchiv.slub-dresden.de/slubarchiv/standards/sigprops/sigprops.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" language="de">
    <Metadata>
        <CreationDate>2022-02-16T09:30:00</CreationDate>
        <Creator>Jens Steidl</Creator>
        <WorkflowName>UBLLDPMuenzen</WorkflowName>
        <InstitutionName>SLUB Dresden</InstitutionName>
        <InstitutionContact>langzeitarchiv@slub-dresden.de</InstitutionContact>
        <ObjectTypeName>Retrodigitalisierte Münzen</ObjectTypeName>
    </Metadata>
    <SignificantProperties>
        <SignificantProperty>
            <PropertyName>Helligkeit und Kontrast</PropertyName>
            <PropertyExplanation>Das Objekt ist hell und kontrastreich (genug), um Details zu erkennen und zu unterscheiden.</PropertyExplanation>
            <PropertyCategory>Rendering</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
        <SignificantProperty>
            <PropertyName>Farbigkeit</PropertyName>
            <PropertyExplanation>Das Objekt ist farbig.</PropertyExplanation>
            <PropertyCategory>Rendering</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
        <SignificantProperty>
            <PropertyName>Farbtreue</PropertyName>
            <PropertyExplanation>Das Objekt ist farbtreu.</PropertyExplanation>
            <PropertyCategory>Rendering</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
        <SignificantProperty>
            <PropertyName>Schärfe</PropertyName>
            <PropertyExplanation>Das Objekt ist scharf abgebildet.</PropertyExplanation>
            <PropertyCategory>Rendering</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
        <SignificantProperty>
            <PropertyName>Auflösung</PropertyName>
            <PropertyExplanation>Das Objekt ist detailliert genug, um jedes Merkmal zu erkennen.</PropertyExplanation>
            <PropertyCategory>Rendering</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
        <SignificantProperty>
            <PropertyName>deskriptive Metadaten</PropertyName>
            <PropertyExplanation>Das Objekt ist beschrieben mit deskriptiven Metadaten.</PropertyExplanation>
            <PropertyCategory>Context</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
        <SignificantProperty>
            <PropertyName>Prüfsummen</PropertyName>
            <PropertyExplanation>Das Objekt ist integer.</PropertyExplanation>
            <PropertyCategory>Context</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
        <SignificantProperty>
            <PropertyName>Proportionen</PropertyName>
            <PropertyExplanation>Das Objekt ist proportionsgetreu.</PropertyExplanation>
            <PropertyCategory>Rendering</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
        <SignificantProperty>
            <PropertyName>Größentreue</PropertyName>
            <PropertyExplanation>Das Objekt ist größengetreu.</PropertyExplanation>
            <PropertyCategory>Structure</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
        <SignificantProperty>
            <PropertyName>Spektraltiefe</PropertyName>
            <PropertyExplanation>Das Objekt ist spektralgetreu.</PropertyExplanation>
            <PropertyCategory>Rendering</PropertyCategory>
            <PropertyProcedure>designated communities</PropertyProcedure>
        </SignificantProperty>
    </SignificantProperties>
</ObjectType>
